services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    # command:
      # - --encryptionEnv #optional
      # - ENCRYPTION #optional
    # environment:
      # ENCRYPTION: example #optional
    ports:
      - "0.0.0.0:8090:8090"
    volumes:
      - ./pb_data:/pb_data